import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const TOOL_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(TOOL_DIR);
const ROSTER_PATH = path.join(ROOT, 'assets/js/hupu/script-01-2678-5hu3djrc-upload-1783494754597-12.js');
const OUTPUT_PATH = path.join(ROOT, 'assets/js/current-player-ratings-2026.js');
const OFFICIAL_TOP100_URL = 'https://nba.2k.com/zh-CN/2k27/top-100-ratings/';

const ATTR_KEYS = ['threePT', 'MID', 'FIN', 'DNK', 'HAN', 'PAS', 'PDEF', 'IDEF', 'BLK', 'REB', 'ATH', 'STR', 'CLU'];

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const number = (value, fallback = 50) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
};
const normalizeName = value => String(value || '')
  .normalize('NFD')
  .replace(/[\u0300-\u036f]/g, '')
  .toLowerCase()
  .replace(/[^a-z0-9]/g, '');

function loadRoster() {
  const sandbox = {};
  vm.createContext(sandbox);
  const source = fs.readFileSync(ROSTER_PATH, 'utf8') + '\n;globalThis.__NBA2K_DATA = NBA2K_DATA;';
  vm.runInContext(source, sandbox, { filename: ROSTER_PATH });
  return sandbox.__NBA2K_DATA;
}

function decodeHtmlEntities(input) {
  return input
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, '\'')
    .replace(/&apos;/g, '\'')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#([0-9]+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)));
}

async function fetchOfficialTop100Ratings() {
  const res = await fetch(OFFICIAL_TOP100_URL);
  if (!res.ok) throw new Error(`Failed to fetch official 2K page: ${res.status}`);
  const html = decodeHtmlEntities(await res.text());

  const pairRegex = /"text":\[0,"(\d+)"\][\s\S]{0,260}?"srcDesktop":\[0,"[^"]+\.(?:svg|png)"\][\s\S]{0,300}?"text":\[0,"([^"]+)"\][\s\S]{0,260}?"text":\[0,"(\d{2}) OVR"\]/g;
  const found = [];
  const byName = new Map();

  let match;
  while ((match = pairRegex.exec(html)) !== null) {
    const name = String(match[2] || '').trim();
    const ovr = clamp(number(match[3], 0), 25, 99);
    if (!name || !/\s/.test(name) || name.length < 4) continue;
    const key = normalizeName(name);
    if (!key) continue;

    if (!byName.has(key)) {
      byName.set(key, { name, ovr });
      found.push({ name, ovr });
    }
  }

  if (found.length < 90) {
    throw new Error(`Official Top100 parse failed: only extracted ${found.length} players.`);
  }
  return found;
}

async function main() {
  const roster = loadRoster();
  const officialTop100 = await fetchOfficialTop100Ratings();
  const officialByName = new Map();
  for (const p of officialTop100) {
    const base = normalizeName(p.name);
    if (base) officialByName.set(base, p.ovr);
    const fixedLeadingC = p.name.replace(/^c([A-Z])/, '$1');
    const alt = normalizeName(fixedLeadingC);
    if (alt) officialByName.set(alt, p.ovr);
  }

  const ratings = {};
  const samples = {};
  let top100MatchedCount = 0;
  const top100Unmatched = [];

  for (const [abbr, teamPlayers] of Object.entries(roster)) {
    for (const p of teamPlayers || []) {
      const key = `${abbr}|${p.name}`;
      const current = { ovr: number(p.ovr, 70), ...Object.fromEntries(ATTR_KEYS.map(attr => [attr, number(p[attr], 50)])) };
      const officialOvr = officialByName.get(normalizeName(p.name));
      if (officialOvr) {
        current.ovr = officialOvr;
        top100MatchedCount++;
      }
      ratings[key] = current;
      samples[key] = { games: 0, minutes: 0, basis: officialOvr ? 'nba2k27-official-top100-ovr' : 'no-official-top100-match' };
    }
  }

  const rosterNameSet = new Set();
  for (const teamPlayers of Object.values(roster)) {
    for (const p of teamPlayers || []) rosterNameSet.add(normalizeName(p.name));
  }
  for (const p of officialTop100) {
    const base = normalizeName(p.name);
    const fixedLeadingC = normalizeName(p.name.replace(/^c([A-Z])/, '$1'));
    if (!rosterNameSet.has(base) && !rosterNameSet.has(fixedLeadingC)) top100Unmatched.push(`${p.name}|${p.ovr}`);
  }

  const meta = {
    season: 'NBA 2K27',
    seasonType: 'Official Top 100 OVR',
    generated: new Date().toISOString().slice(0, 10),
    players: Object.keys(ratings).length,
    officialTop100Count: officialTop100.length,
    top100MatchedCount,
    top100UnmatchedCount: top100Unmatched.length,
    top100Unmatched,
    sources: [OFFICIAL_TOP100_URL],
  };

  const output = `/* Auto-generated by tools/update_current_player_ratings_2k27.mjs. */\n` +
    `const NBA_CURRENT_RATINGS_2026_META = ${JSON.stringify(meta, null, 2)};\n` +
    `const NBA_CURRENT_RATINGS_2026 = ${JSON.stringify(ratings)};\n` +
    `const NBA_CURRENT_RATINGS_2026_SAMPLES = ${JSON.stringify(samples)};\n` +
    `(function applyCurrentPlayerRatings2026() {\n` +
    `  if (typeof NBA2K_DATA === 'undefined') return;\n` +
    `  Object.keys(NBA2K_DATA).forEach(function(team) {\n` +
    `    (NBA2K_DATA[team] || []).forEach(function(player) {\n` +
    `      var key = team + '|' + player.name;\n` +
    `      var rating = NBA_CURRENT_RATINGS_2026[key];\n` +
    `      if (!rating) return;\n` +
    `      Object.keys(rating).forEach(function(attr) { player[attr] = rating[attr]; });\n` +
    `      var sample = NBA_CURRENT_RATINGS_2026_SAMPLES[key] || {};\n` +
    `      player.ratingSeason = NBA_CURRENT_RATINGS_2026_META.season;\n` +
    `      player.ratingBasis = sample.basis || 'nba2k27-official-top100-ovr';\n` +
    `      player.ratingSampleGames = sample.games || 0;\n` +
    `      player.ratingSampleMinutes = sample.minutes || 0;\n` +
    `    });\n` +
    `  });\n` +
    `  if (typeof window !== 'undefined') window.NBA_CURRENT_RATINGS_2026_META = NBA_CURRENT_RATINGS_2026_META;\n` +
    `})();\n`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(JSON.stringify({ output: path.relative(ROOT, OUTPUT_PATH), ...meta }, null, 2));
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
